---
swagger: '2.0'
info:
  title: test
  description: This is a generic API definition for manipulation of order resources.
    It contains basic CRUD operations for order resources.
  version: 1.0
paths:
  /order:
    get:
      summary: Retrieve order resources
      description: Retrieve a bunch of order resources. Specify example resource
        as body payload.
      responses:
        '200':
          description: Get an array of order resources
    post:
      summary: Create new order resource
      description: Create a new order resource. Specify payload within request
        body.
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/orderType"
      responses:
        '201':
          description: Get the newly created order resource.
  /order/:id:
    get:
      summary: Retrieve a order resource.
      description: Retrieve an already existing order resource having the specified
        id.
      responses:
        '200':
          description: "order resource having specified id."
          schema:
            "$ref": "#/definitions/orderType"
        '404':
          description: No order resource have the specified id.
    put:
      summary: Update a order resource.
      description: Update an already existing order resource having the specified
        id.
      parameters:
        - name: body
          in: body
          description: The payload of resource order to update.
          schema:
            "$ref": "#/definitions/orderType"
      responses:
        '200':
          description: Updated resource order having the specified id.
          schema:
            "$ref": "#/definitions/orderType"
    delete:
      summary: Delete a order resource.
      description: Remove an existing order resource having the specified id.
      responses:
        '204':
          description: Resource order with specified id has been removed.
    parameters:
      - name: id
        in: path
        description: Resource order unique identifier.
        type: string
definitions:
  orderType:
    type: object
      properties:
        username:
          type: string
        password:
          type: string
        id:
          type: string
      
